//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public string Emp_CJ { get; set; }
        public int Role_ID { get; set; }
        public string Plant_ID { get; set; }
        public string Description { get; set; }
    
        public virtual Employee_New Employee_New { get; set; }
        public virtual Role Role { get; set; }
    }
}
