//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIZ_TRIP
    {
        public string EMPNO { get; set; }
        public string NAME { get; set; }
        public string DEPT { get; set; }
        public string DESCRIPTION { get; set; }
        public string VEHICLE { get; set; }
        public string CONTACT_COMPANY { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string CONTACT_DEPT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<bool> USED_EQUIPMENT { get; set; }
        public string REMARK { get; set; }
        public string PLANT { get; set; }
        public Nullable<bool> DEPT_CONFIRM { get; set; }
        public byte[] DEPT_CONFIRM_IMAGE { get; set; }
        public Nullable<bool> HR_CONFIRM { get; set; }
        public byte[] HR_CONFIRM_IMAGE { get; set; }
        public Nullable<bool> DEL { get; set; }
        public System.Guid ID { get; set; }
        public int NO { get; set; }
        public Nullable<bool> IT_CONFIRM { get; set; }
        public Nullable<System.DateTime> DEPT_CONFIRM_DATE { get; set; }
        public Nullable<System.DateTime> HR_CONFIRM_DATE { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
