//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJ_HR_RECRUITMENT
    {
        public CJ_HR_RECRUITMENT()
        {
            this.CJ_HR_SALARY_REPORT = new HashSet<CJ_HR_SALARY_REPORT>();
        }
    
        public string EMP_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string JOB { get; set; }
        public string ADDRESS { get; set; }
        public string ID_NUM { get; set; }
        public Nullable<System.DateTime> ID_DATE { get; set; }
        public string ID_PLACE { get; set; }
        public Nullable<decimal> PERIOD { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public string PROMOTION { get; set; }
        public string EMP_LEVEL { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public Nullable<decimal> PERCENT_SALRY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public byte[] ATTACHED_FILE { get; set; }
        public string DEL { get; set; }
        public string PLANT { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string NOTE { get; set; }
        public string CONTRACT_NO { get; set; }
        public bool APPROVE { get; set; }
        public byte[] SIGNATURE_IMAGE { get; set; }
        public bool HR_APPROVE { get; set; }
        public byte[] SIGNATURE_HR_IMAGE { get; set; }
        public Nullable<System.DateTime> HR_APPROVE_DATE { get; set; }
        public bool SALES_APPROVE { get; set; }
        public byte[] SIGNATURE_SALES_IMAGE { get; set; }
        public Nullable<System.DateTime> SALES_APPROVE_DATE { get; set; }
        public Nullable<bool> SALES_EMPLOYEE { get; set; }
    
        public virtual CJ_HR_RECRUITMENT_ACCEPT CJ_HR_RECRUITMENT_ACCEPT { get; set; }
        public virtual ICollection<CJ_HR_SALARY_REPORT> CJ_HR_SALARY_REPORT { get; set; }
    }
}
