//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJ_HR_RECRUITMENT_ACCEPT
    {
        public string EMP_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string JOB { get; set; }
        public string ADDRESS { get; set; }
        public string ID_NUM { get; set; }
        public Nullable<System.DateTime> ID_DATE { get; set; }
        public string ID_PLACE { get; set; }
        public string TYPE_CONTRACT { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string POSITION { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public byte[] ATTACHED_FILE { get; set; }
        public Nullable<bool> DEL { get; set; }
        public string PLANT { get; set; }
        public string NOTE { get; set; }
        public string CONTRACT_NO { get; set; }
        public byte[] SIGNATURE { get; set; }
        public Nullable<bool> APPROVE { get; set; }
        public Nullable<decimal> POSITION_ALLOWANCE { get; set; }
        public Nullable<decimal> TRAINING_ALLOWANCE { get; set; }
        public Nullable<decimal> HAZADOUS { get; set; }
        public Nullable<decimal> LIVING_FARM { get; set; }
        public Nullable<decimal> OMC { get; set; }
        public Nullable<decimal> MEAL { get; set; }
        public Nullable<decimal> PHONE { get; set; }
        public Nullable<decimal> EQUIPMENT_DE { get; set; }
        public Nullable<decimal> PRODUCTIVITY { get; set; }
    
        public virtual CJ_HR_RECRUITMENT CJ_HR_RECRUITMENT { get; set; }
    }
}
