//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT_SUB
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CONTRACTID { get; set; }
        public string SUBNAME { get; set; }
        public byte[] CONTENT { get; set; }
        public string FILE_PATH { get; set; }
        public string PERIODID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string USER_CREATE { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> DEL { get; set; }
        public string PLANT { get; set; }
    
        public virtual CONTRACT CONTRACT { get; set; }
        public virtual PERIOD PERIOD { get; set; }
    }
}
