//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTRACT
    {
        public CONTRACT()
        {
            this.CONTRACT_SUB = new HashSet<CONTRACT_SUB>();
            DATE_CREATE = DateTime.Now;
            DEL = false;
        }
    
        public System.Guid ID { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string VENDOR { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string PERIODID { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string ADREES { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string PHONE { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string REPRESENTATION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public string CONTRACTNAME { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public byte[] CONTENT { get; set; }
        public string NOTE { get; set; }
        public string USER_CREATE { get; set; }
        public string DEPARMENTID { get; set; }
        public Nullable<bool> DEL { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public Nullable<int> MONTHS { get; set; }
        public string CONTRACT_TYPE_ID { get; set; }
        public Nullable<System.DateTime> DATE_MATURITY { get; set; }
        public string PLANT { get; set; }
        public string CONTRACT_TYPE_DT_ID { get; set; }
    
        public virtual CONTRACT_TYPE CONTRACT_TYPE { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PERIOD PERIOD { get; set; }
        public virtual ICollection<CONTRACT_SUB> CONTRACT_SUB { get; set; }
        public virtual CONTRACT_TYPE_DETAIL CONTRACT_TYPE_DETAIL { get; set; }
    }
}
