//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string DepartmentId { get; set; }
        public string Plant { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> Del { get; set; }
        public string Manager_Email { get; set; }
    }
}
