//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Linq;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Document
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public byte[] FileContext { get; set; }
        public string EmployeeID { get; set; }
        public string FileName { get; set; }
        public string DocumentTypeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Del { get; set; }

        [ForeignKey("DocumentTypeId")]
        public virtual DocumentType DocumentType { get; set; }
        [ForeignKey("EmployeeID")]
        public virtual Employee Employee { get; set; }

        public Document()
        {
            Id = Guid.NewGuid();
            Code = create_code();
            Date = DateTime.Now;
            Del = false;
        }

        public static string create_code()
        {
            try
            {
                Web_IT_HELPDESKEntities en = new Web_IT_HELPDESKEntities();
                int ct = (from i in en.Documents select i).Count();
                ct = ct + 1;
                string soct = ct.ToString("000000");
                return soct;
            }
            catch
            {
                //TODO: do something when cannot generate so chung tu
                return "0000001";
            }
        }
    }
}
