//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drinking_Request
    {
        public int Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Department_confirm { get; set; }
        public string Department_note { get; set; }
        public Nullable<System.DateTime> Department_confirm_date { get; set; }
        public bool HR_confirm { get; set; }
        public string HR_note { get; set; }
        public Nullable<System.DateTime> HR_confirm_date { get; set; }
        public bool Del { get; set; }
        public string DepartmentId { get; set; }
        public string Employee_name { get; set; }
    }
}
