//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public Employee()
        {
            this.BIZ_TRIP = new HashSet<BIZ_TRIP>();
            this.Documents = new HashSet<Document>();
            this.EMP_ANSWER = new HashSet<EMP_ANSWER>();
            this.Employee_Screen = new HashSet<Employee_Screen>();
            this.Order_ = new HashSet<Order_>();
            this.UserLogons = new HashSet<UserLogon>();
            this.CONTRACTs = new HashSet<CONTRACT>();
            this.CONTRACT_SUB = new HashSet<CONTRACT_SUB>();
        }

        [Required]
        [Display(Name = "User Login")]
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public string IDNumber { get; set; }
        public string Others { get; set; }
        public string Job { get; set; }
        public string Status_marry { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> datetimeBegin { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public string SearchField { get; set; }
        public Nullable<bool> Del { get; set; }
        public string DepatmentId { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Plant { get; set; }
        public string administrator { get; set; }
    
        public virtual ICollection<BIZ_TRIP> BIZ_TRIP { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<EMP_ANSWER> EMP_ANSWER { get; set; }
        public virtual ICollection<Employee_Screen> Employee_Screen { get; set; }
        public virtual ICollection<Order_> Order_ { get; set; }
        public virtual ICollection<UserLogon> UserLogons { get; set; }
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        public virtual ICollection<CONTRACT_SUB> CONTRACT_SUB { get; set; }
    }
}
