//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo_bk20190826
    {
        public string EMPNO { get; set; }
        public string DEPT_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string GRADE { get; set; }
        public string POSITION_NAME { get; set; }
        public string JOB_NAME { get; set; }
        public string EMP_STATUS { get; set; }
        public string BIRTHDAY { get; set; }
        public string HIRE_DATE { get; set; }
        public string PHONE { get; set; }
        public string EXTENSION { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> DE { get; set; }
        public string DEPT { get; set; }
        public string Email { get; set; }
        public string Plant { get; set; }
    }
}
