//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_bk20190826
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public string IDNumber { get; set; }
        public string Others { get; set; }
        public string Job { get; set; }
        public string Status_marry { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> datetimeBegin { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public string SearchField { get; set; }
        public Nullable<bool> Del { get; set; }
        public string DepatmentId { get; set; }
        public string Password { get; set; }
        public string Plant { get; set; }
        public string administrator { get; set; }
    }
}
