//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_meal
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string EMPNO { get; set; }
        public byte[] IMAGE { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Del { get; set; }
        public string TypeMeal { get; set; }
    }
}
