//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_emp_infor
    {
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string DepartmentId { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Del { get; set; }
    }
}
