//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Linq;

    public partial class Incident
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string StatusId { get; set; }
        public string LevelId { get; set; }
        public string Reply { get; set; }
        public string User_create { get; set; }
        public string User_resolve { get; set; }
        public string Note { get; set; }
        public byte[] FileAttched { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> Del { get; set; }
        public string DepartmentId { get; set; }
        public Nullable<bool> Solved { get; set; }
        public Nullable<System.DateTime> Solve_datetime { get; set; }
        public string Plant { get; set; }

        public Incident()
        {
            Id = Guid.NewGuid();
            Code = create_code();
            datetime = DateTime.Now;
            Solved = false;
            Del = false;

        }

        public static string create_code()
        {
            try
            {
                Web_IT_HELPDESKEntities en = new Web_IT_HELPDESKEntities();
                int ct = (from i in en.Incidents select i).Count();
                ct = ct + 1;
                string soct = ct.ToString("000000");
                return soct;
            }
            catch
            {
                //TODO: do something when cannot generate so chung tu
                return "0000001";
            }
        }
    }
}
