//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public string LevelId { get; set; }
        public string LevelName { get; set; }
        public Nullable<int> datetime_rate { get; set; }
        public Nullable<bool> Del { get; set; }
    }
}
