//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public System.Guid MailID { get; set; }
        public string MailTitle { get; set; }
        public string MailContent { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string CcAddress { get; set; }
        public string BccAddress { get; set; }
        public string Attachment { get; set; }
        public string MailPicture { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public string SendingStatus { get; set; }
        public Nullable<bool> Inactive { get; set; }
    
        public virtual Employee_New Employee_New { get; set; }
    }
}
