//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hr_contract_binhEntities : DbContext
    {
        public hr_contract_binhEntities()
            : base("name=hr_contract_binhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CJ_HR_RECRUITMENT> CJ_HR_RECRUITMENT { get; set; }
        public DbSet<CJ_HR_RECRUITMENT_ACCEPT> CJ_HR_RECRUITMENT_ACCEPT { get; set; }
        public DbSet<CJ_HR_SALARY_REPORT> CJ_HR_SALARY_REPORT { get; set; }
    }
}
