//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [Bind(Exclude = "OrderId")]
    public partial class Order_
    {
        public Order_()
        {
            Confirmed = false;
            OrderDate = DateTime.Now;
        }

        [ScaffoldColumn(false)]
        public int OrderId { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<decimal> Total { get; set; }

        [Required(ErrorMessage = "Note to finish process")]
        public string Note { get; set; }

        [ScaffoldColumn(false)]
        public Nullable<bool> Confirmed { get; set; }

        [ScaffoldColumn(false)]
        public string EmployeeID { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<bool> Del { get; set; }
        public string Plant { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
