//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERIOD()
        {
            this.CONTRACTs = new HashSet<CONTRACT>();
            this.CONTRACT_SUB = new HashSet<CONTRACT_SUB>();
    
            OnConstructorInit();
        }
        partial void OnConstructorInit();
    
        public string PERIOD_ID { get; set; }
        public string PERIOD_NAME { get; set; }
        public Nullable<int> MONTHS { get; set; }
        public Nullable<bool> DEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT> CONTRACTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT_SUB> CONTRACT_SUB { get; set; }
    }
}
