//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public QUESTION()
        {
            this.EMP_ANSWER = new HashSet<EMP_ANSWER>();
        }
    
        public System.Guid ID { get; set; }
        public string NO { get; set; }
        public string QUESTION_CONTENT { get; set; }
        public Nullable<int> ANSWER_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> DEL { get; set; }
    
        public virtual ICollection<EMP_ANSWER> EMP_ANSWER { get; set; }
    }
}
