//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION()
        {
            this.EMP_ANSWER = new HashSet<EMP_ANSWER>();
            OnConstructorInit();
        }
        partial void OnConstructorInit();
    
        public System.Guid ID { get; set; }
        public Nullable<int> No { get; set; }
        public string Outlining { get; set; }
        public string QUESTION_CONTENT { get; set; }
        public Nullable<int> ANSWER_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> DEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ANSWER> EMP_ANSWER { get; set; }
    }
}
