//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rights_Management
    {
        public int Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Rule_Id { get; set; }
        public string Employee_Id { get; set; }
        public string Department_Id { get; set; }
        public string Plant_Id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee_New Employee_New { get; set; }
        public virtual Role Role { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
