//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.Employee_Screen = new HashSet<Employee_Screen>();
        }
    
        public int ScreenId { get; set; }
        public string ScreenName { get; set; }
        public string HTMLcode { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Employee_Screen> Employee_Screen { get; set; }
    }
}
