//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_IT_HELPDESK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seal_Using
    {
        public Seal_Using()
        {
            Date = DateTime.Now;
            Period_date = DateTime.Now;
            Department_confirm = false;
            Employee_Seal_keep_confrim = false;
            Date_signature = DateTime.Now;
            Del = false;
        }

        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Employee_name { get; set; }
        public string Type_document { get; set; }
        public string DepartmentId { get; set; }
        public string Code_number { get; set; }
        public string Context { get; set; }
        public string Place_Recipient { get; set; }
        public Nullable<System.DateTime> Period_date { get; set; }
        public Nullable<System.DateTime> Employee_Seal_keep { get; set; }
        public bool Department_confirm { get; set; }
        public bool Employee_Seal_keep_confrim { get; set; }
        public bool Del { get; set; }
        public string Department_note { get; set; }
        public Nullable<System.DateTime> Department_confirm_date { get; set; }
        public string Employee_Seal_keep_note { get; set; }
        public Nullable<System.DateTime> Date_signature { get; set; }
        public string Name_signature { get; set; }
        public string Plant { get; set; }
    }
}
